apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-gitops
  name: hello-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-gitops
  template:
    metadata:
      labels:
        app: hello-gitops
    spec:
      containers:
        - image: hello-gitops
          name: hello-gitops
          ports:
            - name: http
              containerPort: 8050
              
        - name: hello-gitops
          image: 560136187067.dkr.ecr.us-east-2.amazonaws.com/hello-gitops:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
